# Generated by Django 3.2.5 on 2022-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('BabyEntryId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Pipi', models.BooleanField()),
                ('Caca', models.BooleanField()),
                ('Milk', models.BooleanField()),
                ('MilkQuantity', models.IntegerField()),
            ],
        ),
    ]
