# Generated by Django 3.2.5 on 2022-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
